### ISSUE TITLE
Use this for non Model task requests

### ISSUE THREAD

**Issue by joewheaton** [FluvialHabitatsCenter/etal#1]
@wally-mac

**Comment by wally-mac** [comment]
@Albonicomt, @banderson1618, @CHafen, @chadFHC, @MatthewMeier, @kbartelt, @sshahverdian, @bangen here is the new location for the indexes to use for the various projects we are working on.

Active indexes:

A38321 - Cascadia Research Collective - Yakama BRAT
A40303_USFS - CoOp , Whitebark Pine Beetle Project 
A40529 - BLM - Making Regional Assessments Useful
A40921 - Pheasants Forever - Task 1 Field Workshops
A40922 - Pheasants Forever - Task 2 Design Manual
A40923 - Pheasants Forever - Task 3 Technical Assistance
A41254 - Idaho BRAT
A41150 -BRAT Analysis for John Day Sub-Basin
A41039 - ELR - Asotin
A41581 - Absaroka Beartooth Wilderness Atlas: Cartographic Services
A41211 North Fork Burnt River BRAT
A41309 -TNC Sierra BRAT
A42435 - USFS - GYA BRAT

**Comment by joewheaton** [comment]
@wally-mac I made specific [projects](https://github.com/FluvialHabitatsCenter/etal/projects) for all of these and tried to cross reference where they had [projects in BRAT](https://github.com/Riverscapes/pyBRAT/projects)
